name: Deploy Bosque to WAMP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias y compilar Angular
        run: |
          cd frontend
          npm install
          npm run build
        shell: powershell

      - name: Sincronizar frontend y backend en WAMP
        run: |
          robocopy FRONTEND\dist\frontend\browser C:\wamp64\www\Bosque\FRONTEND\dist\frontend /E /R:3 /W:5
          if %errorlevel% lss 8 exit 0
          
          robocopy BACKEND C:\wamp64\www\Bosque\BACKEND /E /R:3 /W:5
          if %errorlevel% lss 8 exit 0
        shell: cmd